import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import styles from '@/styles/Home.module.css';
// import {home} from '../public/images/home.jpg';

export default function Home() {
  return (
    <>
    <style jsx>
      {
       `
       .mySpan {
        color: red
       }
       ` 
      }
    </style>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
          <div>
            <h1><span className='mySpan'>Blog Post</span></h1>
          </div>
          <div className={styles.imageWrapper}>
          <Image className={styles.myImage} src="/images/home.jpg" height={668} width={1000} alt='Image' />
          </div>
      </main>
    </>
  )
}
